functionsDirectory = "/home/openclaw/.openclaw/workspace/notes-md/netlify/functions"
functionsDirectoryOrigin = "default"
plugins = []
headers = []
redirects = []

[build]
publish = "/home/openclaw/.openclaw/workspace/notes-md"
publishOrigin = "default"
functions = "/home/openclaw/.openclaw/workspace/notes-md/netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]